site_name: Mkdocs Rebalance Theme 
site_description: Rebalance theme from Wordpress translated to mkdocs 
site_url: https://kubilus1.github.io/mkdocs-rebalance-theme/
docs_dir: docs
theme:
    name: rebalance

plugins:
  - search
  - datesort
  - paginate:
      max_items: 6
